server:
  port: 8888
  tomcat:
    connection-timeout: 3s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: cnsa-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/c7haki/cnsa-config
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
